### ISSUE TITLE
YoloWorldの連続使用

### ISSUE THREAD

**Issue by happykoya** [KIT-Happy-Robot/happymimi_recognition#58]
ERROR: service [/recognition_to_grasping] responded with an error: b"service cannot process request: service [/uor/yolo_server] responded with an error: b'error processing request: CUDA out of memory. Tried to allocate 98.00 MiB. GPU 0 has a total capacty of 7.80 GiB of which 68.75 MiB is free. Process 101073 has 2.19 GiB memory in use. Process 143285 has 2.55 GiB memory in use. Including non-PyTorch memory, this process has 2.67 GiB memory in use. Of the allocated memory 1014.51 MiB is allocated by PyTorch, and 7.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF'"

**Comment by Takuchan** [comment]
yolow_server.pyのtry、except:の場所で処理が行われていないで画像が出力されません。２つをコメントアウトしたら画像は出力されました。
@happykoya  @Hiro-Washi

**Comment by Takuchan** [comment]
/detect/depth　が起動していないことによるエラーだということがわかりました

**Comment by Takuchan** [comment]
`position estimator`　が一枚推論したら自動的にノードが終了するらしい。そのためのプログラムを書き直します。

**Comment by Takuchan** [comment]
https://github.com/KIT-Happy-Robot/happymimi_recognition/pull/59
